// Theme Definitions
export const THEMES = {
    default: {
        name: 'Neon',
        unlockScore: 0,
        background: '#0a0a0f',
        player: '#00ffaa',
        playerGlow: 'rgba(0, 255, 170, 0.3)',
        ring: '#ffffff',
        ringPassed: '#00ffaa',
        ringFail: '#ff4466',
        accent: '#00ffaa',
    },
    sunset: {
        name: 'Sunset',
        unlockScore: 10,
        background: '#1a0a1f',
        player: '#ff6b6b',
        playerGlow: 'rgba(255, 107, 107, 0.3)',
        ring: '#ffd93d',
        ringPassed: '#ff6b6b',
        ringFail: '#c44569',
        accent: '#ff6b6b',
    },
    ocean: {
        name: 'Ocean',
        unlockScore: 25,
        background: '#0a1628',
        player: '#4ecdc4',
        playerGlow: 'rgba(78, 205, 196, 0.3)',
        ring: '#a8e6cf',
        ringPassed: '#4ecdc4',
        ringFail: '#ff6b6b',
        accent: '#4ecdc4',
    },
    synthwave: {
        name: 'Synthwave',
        unlockScore: 50,
        background: '#0f0728',
        player: '#f706cf',
        playerGlow: 'rgba(247, 6, 207, 0.3)',
        ring: '#00fff9',
        ringPassed: '#f706cf',
        ringFail: '#ff2a6d',
        accent: '#f706cf',
    },
    monochrome: {
        name: 'Monochrome',
        unlockScore: 75,
        background: '#0a0a0a',
        player: '#ffffff',
        playerGlow: 'rgba(255, 255, 255, 0.2)',
        ring: '#666666',
        ringPassed: '#ffffff',
        ringFail: '#333333',
        accent: '#ffffff',
    },
    gold: {
        name: 'Golden',
        unlockScore: 100,
        background: '#1a1408',
        player: '#ffd700',
        playerGlow: 'rgba(255, 215, 0, 0.3)',
        ring: '#fff8dc',
        ringPassed: '#ffd700',
        ringFail: '#ff4500',
        accent: '#ffd700',
    },
};
